
import { PartType, ViewType, PoseType, AppState, Language } from "./types";

export const VIEW_LABELS = {
  [ViewType.FRONT]: 'FRONT',
  [ViewType.SEMI_SIDE]: 'SEMI-SIDE',
  [ViewType.SIDE]: 'SIDE',
  [ViewType.BACK]: 'BACK',
};

export const POSE_LABELS = {
  [PoseType.A_POSE]: 'A-POSE',
  [PoseType.T_POSE]: 'T-POSE',
  [PoseType.I_POSE]: 'I-POSE',
};

// Canonical English Labels for AI Prompts
export const PART_LABELS: Record<string, string> = {
  [PartType.FACE]: 'Face / Expression',
  [PartType.HAIR]: 'Hair / Style',
  [PartType.HAT]: 'Hat / Headwear',
  [PartType.JACKET]: 'Jacket / Outerwear',
  [PartType.TOP]: 'Top / Inner',
  [PartType.BOTTOM]: 'Bottom / Pants',
  [PartType.SHOES]: 'Shoes / Boots',
  [PartType.GLOVES]: 'Gloves / Hands',
  [PartType.WEAPON]: 'Weapon / Item',
  [PartType.BAG]: 'Bag / Equipment',
  [PartType.ACCESSORY]: 'Accessory / Jewelry',
};

export const TRANSLATIONS = {
  [Language.KO]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.28 • Created by Mookxy",
    copyright_title: "저작권 사용 주의",
    copyright_msg: "타인의 저작물을 무단으로 사용하여 발생하는 모든 문제의 책임은 사용자에게 있습니다. 반드시 본인의 창작물이나 사용 권한이 있는 이미지만을 업로드하여 사용해주세요.",
    usage_guide: "사용 가이드 보기",
    usage_desc: "캐릭터 시트 생성 절차를 자세히 확인합니다.",
    patch_notes: "패치 노트 (v1.28)",
    patch_desc: "최신 업데이트 내역을 확인합니다.",
    view_multi: "4면도 보기",
    view_all: "전체 뷰 보기",
    mode_single: "단일 이미지 모드 (원화만 참고)",
    mode_text: "텍스트로 캐릭터 생성",
    input_prompt: "캐릭터 설명 (Prompt)",
    input_placeholder: "예: 미래적인 사이버펑크 여전사, 네온 블루 자켓, 검은색 카고 팬츠, 붉은색 고글 착용...",
    style_ref: "스타일 참고 (선택)",
    drag_style: "* 이미지를 드래그하거나 붙여넣어 스타일이나 구도를 참고시킬 수 있습니다.",
    pose_select: "표준 포즈 선택 (Pose)",
    part_select: "생성할 파츠 선택",
    custom_part: "기타 파츠 추가...",
    btn_generate_text: "캐릭터 원화 생성",
    btn_analyze_single: "단일 이미지 분석 시작",
    btn_generate_views: "4면도 레퍼런스 생성",
    step0: "Step 0: 텍스트에서 캐릭터 생성 (완료 시 자동으로 Step 1으로 이동)",
    step1_single: "Step 1: 이미지 분석 및 파츠 추출",
    step1_multi: "Step 1: 포즈 정규화 & 4면도(측/반측/후) 자동 생성",
    hint_bottom: "👇 아래 시트에서 [컨셉 시트 생성] 버튼을 눌러 작업을 계속하세요",
    status_waiting: "대기중",
    error_no_ref: "참조 이미지가 없습니다.",
    error_view_fail: "뷰 생성 실패.",
    status_text_gen: "텍스트에서 캐릭터 생성 중...",
    status_ref_check: "레퍼런스 확인 중...",
    status_3q: "입체감 분석을 위한 반측면(3/4) 뷰 생성 중...",
    status_norm: "포즈 정규화 중",
    status_4view: "4면도 완성 중...",
    status_palette: "색상 팔레트 추출 중...",
    status_analyze: "구조 및 색상 분석 중...",
    error_no_part: "분석 결과, 선택한 파츠가 이미지에서 감지되지 않았습니다.",
    status_sheet: "상세 시트 생성 중...",
    error_sheet: "시트 생성 중 오류 발생.",
    error_select_part: "생성할 파츠를 하나 이상 선택해주세요.",
    btn_clean_save: "사진만 병합 저장 (Clean)",
    btn_full_save: "전체 시트 저장 (JPG)",
    header_title: "CHARACTER SHEET",
    header_theme: "Color Theme",
    main_ref: "MAIN REFERENCES",
    analysis_4view: "4-View Analysis",
    reset: "RESET",
    btn_regen_sheet: "시트 재생성",
    btn_gen_sheet: "컨셉 시트 생성",
    style_override: "스타일 참고 (예: 흑백 스케치, 3D 렌더링...)",
    style_note: "* 입력한 스타일을 바탕으로 상세 시트가 생성됩니다. (비워둘 시 원화 스타일 유지)",
    original: "ORIGINAL",
    source: "SOURCE",
    user_upload: "USER UPLOAD",
    palette_title: "PALETTE",
    extracted_colors: "Extracted Colors",
    color: "COLOR",
    source_chips: "Source Chips",
    manual: "MANUAL",
    add: "ADD",
    no_asset: "No Generated Asset",
    generate: "Generate",
    designing: "Designing...",
    analyzing_desc: "Analyzing structure & generating sheet",
    refine_design: "Refine Design",
    applied_changes: "Applied Changes",
    modify_request: "수정 요청",
    confidential: "CONFIDENTIAL ASSET SHEET • DO NOT DISTRIBUTE",
    powered_by: "POWERED BY GOOGLE GEMINI • CREATED BY Mookxy",
    ref_asset_sheet: "Reference Asset Sheet",
    project_ref: "PROJECT: REF-ASSET",
    modal_copyright_title: "저작권 및 사용 권한 확인",
    modal_copyright_body: "업로드하신 이미지가 타인의 저작권을 침해하지 않습니까?\n\nCharSheet AI는 사용자가 업로드한 이미지를 기반으로 새로운 이미지를 생성합니다.\n\n타인의 창작물을 무단으로 사용하여 발생하는 모든 법적 책임은 사용자 본인에게 있습니다.\n반드시 본인의 창작물이나, 사용 권한이 있는 이미지만을 사용하여 진행해주세요.",
    modal_confirm: "네, 확인했습니다. 생성 시작",
    modal_cancel: "취소",
    drop_here: "Drop Here",
    upload: "Upload",
    parts: {
        [PartType.FACE]: '얼굴 / 표정',
        [PartType.HAIR]: '헤어 / 스타일',
        [PartType.HAT]: '모자 / 헤드웨어',
        [PartType.JACKET]: '자켓 / 아우터',
        [PartType.TOP]: '상의 / 이너',
        [PartType.BOTTOM]: '하의 / 팬츠',
        [PartType.SHOES]: '신발 / 부츠',
        [PartType.GLOVES]: '장갑 / 손',
        [PartType.WEAPON]: '무기 / 아이템',
        [PartType.BAG]: '가방 / 장비',
        [PartType.ACCESSORY]: '액세서리 / 장신구',
    },
    views: {
        [ViewType.FRONT]: "정면 뷰 (Front)",
        [ViewType.SEMI_SIDE]: "반측면 뷰 (Semi-Side)",
        [ViewType.SIDE]: "측면 뷰 (Side)",
        [ViewType.BACK]: "후면 뷰 (Back)"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (자연스러운 45도)',
        [PoseType.T_POSE]: 'T-POSE (수평 90도)',
        [PoseType.I_POSE]: 'I-POSE (차렷 자세)',
    }
  },
  [Language.EN]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.28 • Created by Mookxy",
    copyright_title: "Copyright Warning",
    copyright_msg: "You are solely responsible for any issues arising from the unauthorized use of others' work. Please only upload your own creations or images you have permission to use.",
    usage_guide: "How to Use",
    usage_desc: "Learn how to generate character sheets step-by-step.",
    patch_notes: "Patch Notes (v1.28)",
    patch_desc: "Check out the latest updates.",
    view_multi: "4-View Mode",
    view_all: "View All",
    mode_single: "Single Image Mode (Reference Only)",
    mode_text: "Text to Character",
    input_prompt: "Character Description (Prompt)",
    input_placeholder: "e.g., Futuristic cyberpunk warrior, neon blue jacket, black cargo pants, wearing red goggles...",
    style_ref: "Style Reference (Optional)",
    drag_style: "* Drag & drop or paste an image to reference style or composition.",
    pose_select: "Select Standard Pose",
    part_select: "Select Parts to Generate",
    custom_part: "Add Custom Part...",
    btn_generate_text: "Generate Character",
    btn_analyze_single: "Start Single Analysis",
    btn_generate_views: "Generate 4-View Reference",
    step0: "Step 0: Generate character from text (Moves to Step 1 automatically)",
    step1_single: "Step 1: Image Analysis & Part Extraction",
    step1_multi: "Step 1: Pose Normalization & Auto-Generate 4 Views",
    hint_bottom: "👇 Click [Generate Concept Sheet] below to continue",
    status_waiting: "Standby",
    error_no_ref: "No reference image found.",
    error_view_fail: "Failed to generate view.",
    status_text_gen: "Generating character from text...",
    status_ref_check: "Checking references...",
    status_3q: "Generating 3/4 View for volume analysis...",
    status_norm: "Normalizing pose",
    status_4view: "Completing 4-Views...",
    status_palette: "Extracting color palette...",
    status_analyze: "Analyzing structure & colors...",
    error_no_part: "Analysis failed. Selected parts not detected.",
    status_sheet: "Generating detail sheets...",
    error_sheet: "Error generating sheets.",
    error_select_part: "Please select at least one part.",
    btn_clean_save: "Clean Export (Images Only)",
    btn_full_save: "Full Export (JPG Sheet)",
    header_title: "CHARACTER SHEET",
    header_theme: "Color Theme",
    main_ref: "MAIN REFERENCES",
    analysis_4view: "4-View Analysis",
    reset: "RESET",
    btn_regen_sheet: "Regenerate Sheet",
    btn_gen_sheet: "Generate Concept Sheet",
    style_override: "Style Ref (e.g. Sketch, 3D Render...)",
    style_note: "* Detailed sheets will be generated based on this style. (Leave empty to keep original style)",
    original: "ORIGINAL",
    source: "SOURCE",
    user_upload: "USER UPLOAD",
    palette_title: "PALETTE",
    extracted_colors: "Extracted Colors",
    color: "COLOR",
    source_chips: "Source Chips",
    manual: "MANUAL",
    add: "ADD",
    no_asset: "No Generated Asset",
    generate: "Generate",
    designing: "Designing...",
    analyzing_desc: "Analyzing structure & generating sheet",
    refine_design: "Refine Design",
    applied_changes: "Applied Changes",
    modify_request: "Modify",
    confidential: "CONFIDENTIAL ASSET SHEET • DO NOT DISTRIBUTE",
    powered_by: "POWERED BY GOOGLE GEMINI • CREATED BY Mookxy",
    ref_asset_sheet: "Reference Asset Sheet",
    project_ref: "PROJECT: REF-ASSET",
    modal_copyright_title: "Copyright & Usage Confirmation",
    modal_copyright_body: "Does your uploaded image infringe on anyone's copyright?\n\nCharSheet AI generates new images based on what you upload.\n\nYou are solely responsible for any legal issues arising from the unauthorized use of others' creative work.\nPlease verify that you are using your own creation or have permission to use the image.",
    modal_confirm: "Yes, I confirm. Start Generation",
    modal_cancel: "Cancel",
    drop_here: "Drop Here",
    upload: "Upload",
    parts: {
        [PartType.FACE]: 'Face / Expression',
        [PartType.HAIR]: 'Hair / Style',
        [PartType.HAT]: 'Hat / Headwear',
        [PartType.JACKET]: 'Jacket / Outerwear',
        [PartType.TOP]: 'Top / Inner',
        [PartType.BOTTOM]: 'Bottom / Pants',
        [PartType.SHOES]: 'Shoes / Boots',
        [PartType.GLOVES]: 'Gloves / Hands',
        [PartType.WEAPON]: 'Weapon / Item',
        [PartType.BAG]: 'Bag / Equipment',
        [PartType.ACCESSORY]: 'Accessory / Jewelry',
    },
    views: {
        [ViewType.FRONT]: "Front View",
        [ViewType.SEMI_SIDE]: "Semi-Side View",
        [ViewType.SIDE]: "Side View",
        [ViewType.BACK]: "Back View"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (Natural 45°)',
        [PoseType.T_POSE]: 'T-POSE (Horizontal 90°)',
        [PoseType.I_POSE]: 'I-POSE (Straight)',
    }
  },
  [Language.JA]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.28 • Created by Mookxy",
    copyright_title: "著作権に関する注意",
    copyright_msg: "他人の著作物を無断で使用して発生するすべての問題の責任はユーザーにあります。必ずご自身の創作物または使用権限のある画像のみをアップロードして使用してください。",
    usage_guide: "利用ガイド",
    usage_desc: "キャラクターシートの作成手順を確認します。",
    patch_notes: "パッチノート (v1.28)",
    patch_desc: "最新のアップデート内容を確認します。",
    view_multi: "4面図モード",
    view_all: "全ビュー表示",
    mode_single: "単一画像モード (原画のみ参考)",
    mode_text: "テキストからキャラクター生成",
    input_prompt: "キャラクター説明 (Prompt)",
    input_placeholder: "例：未来的なサイバーパンクの女戦士、ネオンブルーのジャケット、黒いカーゴパンツ、赤いゴーグル着用...",
    style_ref: "スタイル参考 (任意)",
    drag_style: "* 画像をドラッグ＆ドロップまたは貼り付けて、スタイルや構図を参考にできます。",
    pose_select: "標準ポーズ選択 (Pose)",
    part_select: "生成パーツ選択",
    custom_part: "その他パーツ追加...",
    btn_generate_text: "キャラクター原画生成",
    btn_analyze_single: "単一画像分析開始",
    btn_generate_views: "4面図リファレンス生成",
    step0: "Step 0: テキストから生成 (完了時に自動でStep 1へ移動)",
    step1_single: "Step 1: 画像分析およびパーツ抽出",
    step1_multi: "Step 1: ポーズ正規化 & 4面図(側/半側/後) 自動生成",
    hint_bottom: "👇 下のシートで [コンセプトシート生成] ボタンを押して作業を続けてください",
    status_waiting: "待機中",
    error_no_ref: "参照画像がありません。",
    error_view_fail: "ビュー生成失敗。",
    status_text_gen: "テキストからキャラクター生成中...",
    status_ref_check: "リファレンス確認中...",
    status_3q: "立体感分析のための半側面(3/4)ビュー生成中...",
    status_norm: "ポーズ正規化中",
    status_4view: "4面図完成中...",
    status_palette: "カラーパレット抽出中...",
    status_analyze: "構造および色彩分析中...",
    error_no_part: "分析の結果、選択したパーツが検出されませんでした。",
    status_sheet: "詳細シート生成中...",
    error_sheet: "シート生成中にエラーが発生しました。",
    error_select_part: "生成するパーツを1つ以上選択してください。",
    btn_clean_save: "画像のみ結合保存 (Clean)",
    btn_full_save: "全体シート保存 (JPG)",
    header_title: "CHARACTER SHEET",
    header_theme: "Color Theme",
    main_ref: "MAIN REFERENCES",
    analysis_4view: "4-View Analysis",
    reset: "RESET",
    btn_regen_sheet: "シート再生成",
    btn_gen_sheet: "コンセプトシート生成",
    style_override: "スタイル参考 (例: 白黒スケッチ, 3Dレンダリング...)",
    style_note: "* 入力したスタイルを基に詳細シートが生成されます。(空欄の場合は原画スタイル維持)",
    original: "ORIGINAL",
    source: "SOURCE",
    user_upload: "USER UPLOAD",
    palette_title: "PALETTE",
    extracted_colors: "Extracted Colors",
    color: "COLOR",
    source_chips: "Source Chips",
    manual: "MANUAL",
    add: "ADD",
    no_asset: "No Generated Asset",
    generate: "Generate",
    designing: "Designing...",
    analyzing_desc: "Analyzing structure & generating sheet",
    refine_design: "Refine Design",
    applied_changes: "Applied Changes",
    modify_request: "修正リクエスト",
    confidential: "CONFIDENTIAL ASSET SHEET • DO NOT DISTRIBUTE",
    powered_by: "POWERED BY GOOGLE GEMINI • CREATED BY Mookxy",
    ref_asset_sheet: "Reference Asset Sheet",
    project_ref: "PROJECT: REF-ASSET",
    modal_copyright_title: "著作権および使用権限の確認",
    modal_copyright_body: "アップロードした画像は他人の著作権を侵害していませんか？\n\nCharSheet AIは、アップロードされた画像を基に新しい画像を生成します。\n\n他人の創作物を無断で使用して発生するすべての法的責任はユーザー本人にあります。\n必ずご自身の創作物、または使用権限のある画像のみを使用して進めてください。",
    modal_confirm: "はい、確認しました。生成開始",
    modal_cancel: "キャンセル",
    drop_here: "Drop Here",
    upload: "Upload",
    parts: {
        [PartType.FACE]: '顔 / 表情',
        [PartType.HAIR]: '髪 / スタイル',
        [PartType.HAT]: '帽子 / ヘッドウェア',
        [PartType.JACKET]: 'ジャケット / アウター',
        [PartType.TOP]: 'トップス / インナー',
        [PartType.BOTTOM]: 'ボトムス / パンツ',
        [PartType.SHOES]: '靴 / ブーツ',
        [PartType.GLOVES]: '手袋 / 手',
        [PartType.WEAPON]: '武器 / アイテム',
        [PartType.BAG]: 'バッグ / 装備',
        [PartType.ACCESSORY]: 'アクセサリー / 装飾',
    },
    views: {
        [ViewType.FRONT]: "正面ビュー (Front)",
        [ViewType.SEMI_SIDE]: "半側面ビュー (Semi-Side)",
        [ViewType.SIDE]: "側面ビュー (Side)",
        [ViewType.BACK]: "背面ビュー (Back)"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (自然な45度)',
        [PoseType.T_POSE]: 'T-POSE (水平90度)',
        [PoseType.I_POSE]: 'I-POSE (直立)',
    }
  },
  [Language.ZH]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.28 • Created by Mookxy",
    copyright_title: "版权警告",
    copyright_msg: "因擅自使用他人作品而产生的一切问题由用户承担。请务必仅上传本人的创作或拥有使用权限的图片。",
    usage_guide: "使用指南",
    usage_desc: "查看详细的角色表生成步骤。",
    patch_notes: "更新日志 (v1.28)",
    patch_desc: "查看最新更新内容。",
    view_multi: "四视图模式",
    view_all: "查看全部",
    mode_single: "单图模式 (仅参考原画)",
    mode_text: "文本生成角色",
    input_prompt: "角色描述 (Prompt)",
    input_placeholder: "例如：未来赛博朋克女战士，霓虹蓝夹克，黑色工装裤，佩戴红色护目镜...",
    style_ref: "风格参考 (可选)",
    drag_style: "* 拖拽或粘贴图片以参考风格或构图。",
    pose_select: "选择标准姿势 (Pose)",
    part_select: "选择生成部位",
    custom_part: "添加其他部位...",
    btn_generate_text: "生成角色原画",
    btn_analyze_single: "开始单图分析",
    btn_generate_views: "生成四视图参考",
    step0: "Step 0: 从文本生成角色 (完成后自动进入Step 1)",
    step1_single: "Step 1: 图像分析及部位提取",
    step1_multi: "Step 1: 姿势标准化 & 自动生成四视图(侧/半侧/后)",
    hint_bottom: "👇 点击下方的 [生成概念图] 按钮继续操作",
    status_waiting: "待机中",
    error_no_ref: "未找到参考图片。",
    error_view_fail: "视图生成失败。",
    status_text_gen: "正在从文本生成角色...",
    status_ref_check: "正在检查参考...",
    status_3q: "正在生成用于立体感分析的半侧面(3/4)视图...",
    status_norm: "正在标准化姿势",
    status_4view: "正在完成四视图...",
    status_palette: "正在提取调色板...",
    status_analyze: "正在分析结构与色彩...",
    error_no_part: "分析结果：未检测到选定的部位。",
    status_sheet: "正在生成详细图表...",
    error_sheet: "生成图表时发生错误。",
    error_select_part: "请至少选择一个部位。",
    btn_clean_save: "仅保存图片拼接 (Clean)",
    btn_full_save: "保存完整图表 (JPG)",
    header_title: "CHARACTER SHEET",
    header_theme: "Color Theme",
    main_ref: "MAIN REFERENCES",
    analysis_4view: "4-View Analysis",
    reset: "RESET",
    btn_regen_sheet: "重新生成图表",
    btn_gen_sheet: "生成概念图",
    style_override: "风格参考 (例: 黑白草图, 3D渲染...)",
    style_note: "* 将根据输入的风格生成详细图表。(留空则保持原画风格)",
    original: "ORIGINAL",
    source: "SOURCE",
    user_upload: "USER UPLOAD",
    palette_title: "PALETTE",
    extracted_colors: "Extracted Colors",
    color: "COLOR",
    source_chips: "Source Chips",
    manual: "MANUAL",
    add: "ADD",
    no_asset: "No Generated Asset",
    generate: "Generate",
    designing: "Designing...",
    analyzing_desc: "Analyzing structure & generating sheet",
    refine_design: "Refine Design",
    applied_changes: "Applied Changes",
    modify_request: "修改请求",
    confidential: "CONFIDENTIAL ASSET SHEET • DO NOT DISTRIBUTE",
    powered_by: "POWERED BY GOOGLE GEMINI • CREATED BY Mookxy",
    ref_asset_sheet: "Reference Asset Sheet",
    project_ref: "PROJECT: REF-ASSET",
    modal_copyright_title: "版权及使用权限确认",
    modal_copyright_body: "您上传的图片是否侵犯了他人的版权？\n\nCharSheet AI 基于您上传的图片生成新图像。\n\n因擅自使用他人创作而产生的一切法律责任由用户本人承担。\n请务必确认使用的是本人的创作或拥有使用权限的图片。",
    modal_confirm: "是的，我确认。开始生成",
    modal_cancel: "取消",
    drop_here: "Drop Here",
    upload: "Upload",
    parts: {
        [PartType.FACE]: '脸部 / 表情',
        [PartType.HAIR]: '发型 / 风格',
        [PartType.HAT]: '帽子 / 头饰',
        [PartType.JACKET]: '外套 / 大衣',
        [PartType.TOP]: '上衣 / 内搭',
        [PartType.BOTTOM]: '下装 / 裤子',
        [PartType.SHOES]: '鞋 / 靴子',
        [PartType.GLOVES]: '手套 / 手',
        [PartType.WEAPON]: '武器 / 道具',
        [PartType.BAG]: '包 / 装备',
        [PartType.ACCESSORY]: '饰品 / 珠宝',
    },
    views: {
        [ViewType.FRONT]: "正面视图 (Front)",
        [ViewType.SEMI_SIDE]: "半侧面视图 (Semi-Side)",
        [ViewType.SIDE]: "侧面视图 (Side)",
        [ViewType.BACK]: "背面视图 (Back)"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (自然45度)',
        [PoseType.T_POSE]: 'T-POSE (水平90度)',
        [PoseType.I_POSE]: 'I-POSE (直立)',
    }
  },
};

export const INITIAL_VIEW_STATE = (id: ViewType) => ({
  id,
  label: VIEW_LABELS[id],
  originalImage: null,
  userUploadedImage: null,
  parts: {
    [PartType.FACE]: null,
    [PartType.HAIR]: null,
    [PartType.HAT]: null,
    [PartType.JACKET]: null,
    [PartType.TOP]: null,
    [PartType.BOTTOM]: null,
    [PartType.SHOES]: null,
    [PartType.GLOVES]: null,
    [PartType.WEAPON]: null,
    [PartType.BAG]: null,
    [PartType.ACCESSORY]: null,
  },
  modifications: [],
});

export const getInitialAppState = (): AppState => ({
  views: {
    [ViewType.FRONT]: INITIAL_VIEW_STATE(ViewType.FRONT),
    [ViewType.SEMI_SIDE]: INITIAL_VIEW_STATE(ViewType.SEMI_SIDE),
    [ViewType.SIDE]: INITIAL_VIEW_STATE(ViewType.SIDE),
    [ViewType.BACK]: INITIAL_VIEW_STATE(ViewType.BACK),
  },
  generatedSheets: {
    [PartType.FACE]: { partType: PartType.FACE, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.HAIR]: { partType: PartType.HAIR, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.HAT]: { partType: PartType.HAT, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.JACKET]: { partType: PartType.JACKET, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.TOP]: { partType: PartType.TOP, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.BOTTOM]: { partType: PartType.BOTTOM, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.SHOES]: { partType: PartType.SHOES, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.GLOVES]: { partType: PartType.GLOVES, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.WEAPON]: { partType: PartType.WEAPON, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.BAG]: { partType: PartType.BAG, imgUrl: null, isLoading: false, modifications: [] },
    [PartType.ACCESSORY]: { partType: PartType.ACCESSORY, imgUrl: null, isLoading: false, modifications: [] },
  },
  manualReferences: {
    [PartType.FACE]: [],
    [PartType.HAIR]: [],
    [PartType.HAT]: [],
    [PartType.JACKET]: [],
    [PartType.TOP]: [],
    [PartType.BOTTOM]: [],
    [PartType.SHOES]: [],
    [PartType.GLOVES]: [],
    [PartType.WEAPON]: [],
    [PartType.BAG]: [],
    [PartType.ACCESSORY]: [],
  },
  customParts: [],
  colorPalette: [],
  globalStylePrompt: "",
});
