
import { PartType, ViewType, PoseType, AppState, Language, CharacterView, GeneratedPartSheet } from "../types";

export const VIEW_LABELS = {
  [ViewType.FRONT]: 'FRONT',
  [ViewType.SEMI_SIDE]: 'SEMI-SIDE',
  [ViewType.SIDE]: 'SIDE',
  [ViewType.BACK]: 'BACK',
};

export const POSE_LABELS = {
  [PoseType.A_POSE]: 'A-POSE',
  [PoseType.T_POSE]: 'T-POSE',
  [PoseType.I_POSE]: 'I-POSE',
};

// Canonical English Labels for AI Prompts
export const PART_LABELS: Record<string, string> = {
  [PartType.FACE]: 'Face / Expression',
  [PartType.HAIR]: 'Hair / Style',
  [PartType.HAT]: 'Hat / Headwear',
  [PartType.JACKET]: 'Jacket / Outerwear',
  [PartType.TOP]: 'Top / Inner',
  [PartType.BOTTOM]: 'Bottom / Pants',
  [PartType.SHOES]: 'Shoes / Boots',
  [PartType.GLOVES]: 'Gloves / Hands',
  [PartType.WEAPON]: 'Weapon / Item',
  [PartType.BAG]: 'Bag / Equipment',
  [PartType.ACCESSORY]: 'Accessory / Jewelry',
};

export const INITIAL_VIEW_STATE = (view: ViewType): CharacterView => ({
  id: view,
  label: VIEW_LABELS[view],
  originalImage: null,
  userUploadedImage: null,
  generatedImage: null,
  parts: {},
  modifications: [],
  history: { undoStack: [], redoStack: [] }
});

export const getInitialAppState = (): AppState => {
  const initialGeneratedSheets: Record<string, GeneratedPartSheet> = {};
  (Object.values(PartType) as string[]).forEach(part => {
    initialGeneratedSheets[part] = {
      partType: part,
      imgUrl: null,
      isLoading: false,
      modifications: [],
      history: { undoStack: [], redoStack: [] }
    };
  });

  return {
    views: {
      [ViewType.FRONT]: INITIAL_VIEW_STATE(ViewType.FRONT),
      [ViewType.SEMI_SIDE]: INITIAL_VIEW_STATE(ViewType.SEMI_SIDE),
      [ViewType.SIDE]: INITIAL_VIEW_STATE(ViewType.SIDE),
      [ViewType.BACK]: INITIAL_VIEW_STATE(ViewType.BACK),
    },
    generatedSheets: initialGeneratedSheets,
    manualReferences: {},
    customParts: [],
    colorPalette: [],
    globalStylePrompt: "",
    originalParts: {}, 
  };
};

export const TRANSLATIONS = {
  [Language.KO]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.34 • Created by Mookxy • snu07001@naver.com",
    copyright_title: "저작권 사용 주의",
    copyright_msg: "타인의 저작물을 무단으로 사용하여 발생하는 모든 문제의 책임은 사용자에게 있습니다. 반드시 본인의 창작물이나 사용 권한이 있는 이미지만을 업로드하여 사용해주세요.",
    usage_guide: "사용 가이드 보기",
    usage_desc: "캐릭터 시트 생성 절차를 자세히 확인합니다.",
    patch_notes: "패치 노트 (v1.34)",
    patch_desc: "최신 업데이트 내역을 확인합니다.",
    view_multi: "멀티 뷰 (Multi View)",
    view_all: "싱글 뷰 (Single View)",
    mode_single: "단일 이미지 모드 (원화만 참고)",
    mode_text: "텍스트로 캐릭터 생성",
    input_prompt: "캐릭터 설명 (Prompt)",
    input_placeholder: "예: 미래적인 사이버펑크 여전사, 네온 블루 자켓, 검은색 카고 팬츠, 붉은색 고글 착용...",
    style_ref: "스타일 참고 (선택)",
    drag_style: "* 이미지를 드래그하거나 붙여넣어 스타일이나 구도를 참고시킬 수 있습니다.",
    pose_select: "표준 포즈 선택 (Pose)",
    part_select: "생성할 파츠 선택",
    custom_part: "기타 파츠 추가...",
    btn_generate_text: "캐릭터 원화 생성",
    btn_analyze_single: "단일 이미지 분석 시작",
    btn_generate_views: "4면도 레퍼런스 생성",
    step0: "Step 0: 텍스트에서 캐릭터 생성 (완료 시 자동으로 Step 1으로 이동)",
    step1_single: "Step 1: 이미지 분석 및 파츠 추출",
    step1_multi: "Step 1: 포즈 정규화 & 4면도(측/반측/후) 자동 생성",
    hint_bottom: "👇 아래 시트에서 [컨셉 시트 생성] 버튼을 눌러 작업을 계속하세요",
    status_waiting: "대기중",
    error_no_ref: "참조 이미지가 없습니다.",
    error_view_fail: "뷰 생성 실패.",
    status_text_gen: "텍스트에서 캐릭터 생성 중...",
    status_ref_check: "레퍼런스 확인 중...",
    status_3q: "입체감 분석을 위한 반측면(3/4) 뷰 생성 중...",
    status_norm: "포즈 정규화 중",
    status_4view: "4면도 완성 중...",
    status_palette: "색상 팔레트 추출 중...",
    status_analyze: "구조 및 색상 분석 중...",
    error_no_part: "분석 결과, 선택한 파츠가 이미지에서 감지되지 않았습니다.",
    status_sheet: "상세 시트 생성 중...",
    error_sheet: "시트 생성 중 오류 발생.",
    error_select_part: "생성할 파츠를 하나 이상 선택해주세요.",
    btn_zip_save: "전체 압축 저장 (ZIP)",
    btn_clean_save: "사진만 병합 저장 (Clean)",
    btn_full_save: "전체 시트 저장 (JPG)",
    btn_upscale: "업스케일 (4K)",
    dl_zip_desc: "모든 파츠 개별 파일 압축",
    dl_clean_desc: "텍스트 제외 자산만 병합",
    dl_full_desc: "전체 화면 캡처 저장",
    header_title: "캐릭터 시트",
    header_theme: "색상 테마",
    main_ref: "메인 레퍼런스",
    analysis_4view: "4면도 정밀 분석",
    reset: "초기화",
    btn_regen_sheet: "시트 재생성",
    btn_gen_sheet: "컨셉 시트 생성",
    style_override: "스타일 참고 (예: 흑백 스케치, 3D 렌더링...)",
    style_note: "* 입력한 스타일을 바탕으로 상세 시트가 생성됩니다. (비워둘 시 원화 스타일 유지)",
    upscale_hint: "* 4면도를 모두 업스케일을 하신 후에 시트를 생성하면 더 디테일한 결과물을 얻을 수 있습니다.",
    ref_balance_note: "* 참조 비율: [원본]에 가까울수록 업로드한 이미지를, [생성본]에 가까울수록 AI가 생성한 4면도를 더 많이 반영합니다.",
    style_ref_note: "* 스타일 참고: 텍스트 입력창에 원하는 화풍(예: 3D 렌더링, 픽셀 아트)を 입력하면 시트의 스타일이 변경됩니다.",
    original: "원본",
    source: "출처",
    user_upload: "사용자 업로드",
    palette_title: "색상 팔레트",
    extracted_colors: "추출된 색상 코드",
    color: "색상",
    source_chips: "참조 이미지",
    manual: "수동",
    add: "추가",
    no_asset: "생성된 이미지 없음",
    generate: "생성하기",
    designing: "디자인 생성 중...",
    analyzing_desc: "구조 분석 및 시트 생성 중",
    refine_design: "디자인 수정하기",
    applied_changes: "적용된 수정사항",
    modify_request: "수정 요청",
    confidential: "대외비 자산 시트 • 무단 배포 금지",
    powered_by: "Google Gemini 기반 • 제작: Mookxy",
    ref_asset_sheet: "레퍼런스 자산 시트",
    project_ref: "프로젝트: 참조 자산",
    modal_copyright_title: "저작권 및 사용 권한 확인",
    modal_copyright_body: "업로드하신 이미지가 타인의 저작권을 침해하지 않습니까?\n\nCharSheet AI는 사용자가 업로드한 이미지를 기반으로 새로운 이미지를 생성합니다.\n\n타인의 창작물을 무단으로 사용하여 발생하는 모든 법적 책임은 사용자 본인에게 있습니다.\n반드시 본인의 창작물이나, 사용 권한이 있는 이미지만을 사용하여 진행해주세요.",
    modal_confirm: "네, 확인했습니다. 생성 시작",
    modal_cancel: "취소",
    drop_here: "이미지 놓기",
    upload: "업로드",
    analysis_label: "분석",
    buy_coffee: "개발자에게 커피 사주기 ☕",
    coffee_modal_title: "개발자 응원하기",
    coffee_modal_body: "Charsheet AI가 도움이 되셨나요?\n여러분의 작은 후원이 지속적인 서비스 운영과\n새로운 기능 개발에 큰 힘이 됩니다!",
    btn_coffee_link: "커피 한 잔 후원하기 (aCoffee)",
    btn_compare: "원본과 비교",
    part_desc_gloves: "손등 및 손바닥 뷰 포함. 재질 텍스처 디테일.",
    part_desc_top: "A-Pose 의상 시뮬레이션 분리. 재봉선 및 주름 분석.",
    part_desc_bottom: "하의 분리. 스티치 및 주머니 배치.",
    part_desc_jacket: "외부 레이어 분리. 안감 및 여밈 구조.",
    part_desc_face: "표정 시트: 정면, 반측면, 측면 뷰 포함.",
    part_desc_hair: "구조 분석: 전체적인 볼륨, 흐름 및 헤어라인.",
    part_desc_bag: "스트랩 연결부, 버클, 수납 공간 시각화.",
    part_desc_accessory: "복잡한 형상의 매크로 줌. 크기 비례 참조.",
    part_desc_shoes: "신발의 정면, 측면, 후면, 밑창 디테일.",
    part_desc_weapon: "전체 형태 및 그립/날 부분 확대.",
    part_desc_custom: "사용자 지정 세부 사항 요청.",
    part_desc_standard: "표준 평면 투영.",
    parts: {
        [PartType.FACE]: '얼굴 / 표정',
        [PartType.HAIR]: '헤어 / 스타일',
        [PartType.HAT]: '모자 / 헤드웨어',
        [PartType.JACKET]: '자켓 / 아우터',
        [PartType.TOP]: '상의 / 이너',
        [PartType.BOTTOM]: '하의 / 팬츠',
        [PartType.SHOES]: '신발 / 부츠',
        [PartType.GLOVES]: '장갑 / 손',
        [PartType.WEAPON]: '무기 / 아이템',
        [PartType.BAG]: '가방 / 장비',
        [PartType.ACCESSORY]: '액세서리 / 장신구',
    },
    views: {
        [ViewType.FRONT]: "정면 (Front)",
        [ViewType.SEMI_SIDE]: "반측면 (Semi-Side)",
        [ViewType.SIDE]: "측면 (Side)",
        [ViewType.BACK]: "후면 (Back)"
    },
    view_labels: {
        [ViewType.FRONT]: "정면",
        [ViewType.SEMI_SIDE]: "반측면",
        [ViewType.SIDE]: "측면",
        [ViewType.BACK]: "후면"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (자연스러운 45도)',
        [PoseType.T_POSE]: 'T-POSE (수평 90도)',
        [PoseType.I_POSE]: 'I-POSE (차렷 자세)',
    },
    usage_steps: [
      {
        title: "캐릭터 원화 준비 (입력)",
        desc: "캐릭터의 정면 전신 이미지를 업로드하거나, 텍스트 프롬프트를 사용하여 새로운 캐릭터를 생성하세요.",
        bullets: [
          "배경이 복잡하지 않은 이미지가 인식률이 높습니다.",
          "A-Pose(팔을 살짝 벌린 자세)가 가장 이상적입니다."
        ]
      },
      {
        title: "4면도 레퍼런스 생성 (Step 1)",
        desc: "[4면도 레퍼런스 생성] 버튼을 클릭하면 AI가 캐릭터의 측면, 후면, 반측면(45도) 뷰를 자동으로 생성합니다.",
        bullets: [
          "이 과정에서 캐릭터의 자세가 표준 포즈(A-Pose/T-Pose)로 정규화됩니다.",
          "생성된 각 뷰는 '수정 요청' 기능을 통해 재생성하거나 디테일을 다듬을 수 있습니다."
        ]
      },
      {
        title: "파츠 선택 및 시트 생성 (Step 2)",
        desc: "상세 도면이 필요한 부위(의상, 무기, 얼굴 등)를 선택하세요.",
        bullets: [
          "표준 파츠 외에 '기타 파츠' 입력창에 원하는 부위(예: 기계 팔, 망토)를 입력하여 추가할 수 있습니다.",
          "[컨셉 시트 생성] 버튼을 누르면 선택한 각 파츠에 대한 상세 분석 시트가 생성됩니다."
        ]
      },
      {
        title: "결과물 내보내기",
        desc: "완성된 시트는 JPG 이미지로 통째로 저장하거나, 깔끔하게 정리된 자산(Asset) 페이지만 별도로 저장할 수 있습니다.",
        bullets: []
      }
    ],
    patch_notes_list: [
      { version: "v1.34", desc: "Update: 업스케일 로직 개선 (스타일 유지 강화). 저장 버튼 설명 추가." },
      { version: "v1.33", desc: "Feature: 부분/전체 업스케일(4K) 기능 추가. 부분 재생성(Undo/Redo) 추가." },
      { version: "v1.32", desc: "Feature: 레퍼런스 밸런스 슬라이더 추가. 배치 작업(Batch Action) 지원." },
      { version: "v1.29", desc: "Update: 전체 UI 한글화 적용. '개발자에게 커피 사주기' 후원 기능 추가." },
      { version: "v1.28", desc: "Feature: 다국어 지원 추가 (한국어, English, 日本語, 中文)." }
    ],
    batch_upscale: "선택 항목 업스케일",
    batch_regenerate: "선택 항목 재생성",
    ref_balance_title: "레퍼런스 밸런스 (Reference Balance)",
    ref_original: "원본 중시",
    ref_generated: "생성본 중시",
    batch_parts_undo: "전체 실행취소",
    batch_parts_redo: "전체 다시실행",
    batch_parts_upscale: "전체 업스케일",
    batch_parts_regen: "전체 재생성",
    btn_use_generated: "생성본 사용",
    btn_use_original: "업로드본 사용",
  },
  [Language.EN]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.34 • Created by Mookxy • snu07001@naver.com",
    copyright_title: "Copyright Warning",
    copyright_msg: "You are solely responsible for any issues arising from the unauthorized use of others' work. Please only upload your own creations or images you have permission to use.",
    usage_guide: "How to Use",
    usage_desc: "Learn how to generate character sheets step-by-step.",
    patch_notes: "Patch Notes",
    patch_desc: "Check out the latest updates.",
    view_multi: "4-View Mode",
    view_all: "View All",
    mode_single: "Single Image Mode (Reference Only)",
    mode_text: "Text to Character",
    input_prompt: "Character Description (Prompt)",
    input_placeholder: "e.g., Futuristic cyberpunk warrior, neon blue jacket, black cargo pants, wearing red goggles...",
    style_ref: "Style Reference (Optional)",
    drag_style: "* Drag & drop or paste an image to reference style or composition.",
    pose_select: "Select Standard Pose",
    part_select: "Select Parts to Generate",
    custom_part: "Add Custom Part...",
    btn_generate_text: "Generate Character",
    btn_analyze_single: "Start Single Analysis",
    btn_generate_views: "Generate 4-View Reference",
    step0: "Step 0: Generate character from text (Moves to Step 1 automatically)",
    step1_single: "Step 1: Image Analysis & Part Extraction",
    step1_multi: "Step 1: Pose Normalization & Auto-Generate 4 Views",
    hint_bottom: "👇 Click [Generate Concept Sheet] below to continue",
    status_waiting: "Standby",
    error_no_ref: "No reference image found.",
    error_view_fail: "Failed to generate view.",
    status_text_gen: "Generating character from text...",
    status_ref_check: "Checking references...",
    status_3q: "Generating 3/4 View for volume analysis...",
    status_norm: "Normalizing pose",
    status_4view: "Completing 4-Views...",
    status_palette: "Extracting color palette...",
    status_analyze: "Analyzing structure & colors...",
    error_no_part: "Analysis failed. Selected parts not detected.",
    status_sheet: "Generating detail sheets...",
    error_sheet: "Error generating sheets.",
    error_select_part: "Please select at least one part.",
    btn_clean_save: "Clean Export (Images Only)",
    btn_full_save: "Full Export (JPG Sheet)",
    btn_zip_save: "Save as ZIP",
    btn_upscale: "Upscale (4K)",
    dl_zip_desc: "Compressed archive of all individual parts",
    dl_clean_desc: "Merged assets without text labels",
    dl_full_desc: "Full screen capture of the sheet",
    header_title: "CHARACTER SHEET",
    header_theme: "Color Theme",
    main_ref: "MAIN REFERENCES",
    analysis_4view: "4-View Analysis",
    reset: "RESET",
    btn_regen_sheet: "Regenerate Sheet",
    btn_gen_sheet: "Generate Concept Sheet",
    style_override: "Style Ref (e.g. Sketch, 3D Render...)",
    style_note: "* Detailed sheets will be generated based on this style. (Leave empty to keep original style)",
    upscale_hint: "* Upscaling all 4 views before generating the sheet yields more detailed results.",
    ref_balance_note: "* Reference Balance: Closer to [Original] uses your upload; closer to [Generated] uses AI views.",
    style_ref_note: "* Style Ref: Input a style (e.g. 3D Render, Pixel Art) to change the sheet's art style.",
    original: "ORIGINAL",
    source: "SOURCE",
    user_upload: "USER UPLOAD",
    palette_title: "PALETTE",
    extracted_colors: "Extracted Colors",
    color: "COLOR",
    source_chips: "Source Chips",
    manual: "MANUAL",
    add: "ADD",
    no_asset: "No Generated Asset",
    generate: "Generate",
    designing: "Designing...",
    analyzing_desc: "Analyzing structure & generating sheet",
    refine_design: "Refine Design",
    applied_changes: "Applied Changes",
    modify_request: "Modify",
    confidential: "CONFIDENTIAL ASSET SHEET • DO NOT DISTRIBUTE",
    powered_by: "POWERED BY GOOGLE GEMINI • CREATED BY Mookxy",
    ref_asset_sheet: "Reference Asset Sheet",
    project_ref: "PROJECT: REF-ASSET",
    modal_copyright_title: "Copyright & Usage Confirmation",
    modal_copyright_body: "Does your uploaded image infringe on anyone's copyright?\n\nCharSheet AI generates new images based on what you upload.\n\nYou are solely responsible for any legal issues arising from the unauthorized use of others' creative work.\nPlease verify that you are using your own creation or have permission to use the image.",
    modal_confirm: "Yes, I confirm. Start Generation",
    modal_cancel: "Cancel",
    drop_here: "Drop Here",
    upload: "Upload",
    analysis_label: "ANALYSIS",
    buy_coffee: "Buy me a coffee ☕",
    coffee_modal_title: "Support the Developer",
    coffee_modal_body: "Did you find CharSheet AI useful?\nYour support helps keep the servers running and new features coming!",
    btn_coffee_link: "Buy me a coffee (aCoffee)",
    btn_compare: "Compare Original",
    part_desc_gloves: "Includes Dorsal & Palm views. Detailing material texture.",
    part_desc_top: "Isolated A-Pose garment simulation. Seam & fold analysis.",
    part_desc_bottom: "Isolated garment. Stitching & pocket placement.",
    part_desc_jacket: "Outer layer isolation. Lining & closure mechanics.",
    part_desc_face: "Expression Sheet: Front, 3/4, Profile.",
    part_desc_hair: "Structure Analysis: Volume, flow, and hairline.",
    part_desc_bag: "Strap connection points, buckles, capacity visualization.",
    part_desc_accessory: "Macro zoom on complex geometry. Scale reference.",
    part_desc_shoes: "Front, Side, Back, Sole detailing.",
    part_desc_weapon: "Full form plus grip/edge magnification.",
    part_desc_custom: "Custom specific detailing requested.",
    part_desc_standard: "Standard orthographic projection.",
    parts: {
        [PartType.FACE]: 'Face / Expression',
        [PartType.HAIR]: 'Hair / Style',
        [PartType.HAT]: 'Hat / Headwear',
        [PartType.JACKET]: 'Jacket / Outerwear',
        [PartType.TOP]: 'Top / Inner',
        [PartType.BOTTOM]: 'Bottom / Pants',
        [PartType.SHOES]: 'Shoes / Boots',
        [PartType.GLOVES]: 'Gloves / Hands',
        [PartType.WEAPON]: 'Weapon / Item',
        [PartType.BAG]: 'Bag / Equipment',
        [PartType.ACCESSORY]: 'Accessory / Jewelry',
    },
    views: {
        [ViewType.FRONT]: "Front View",
        [ViewType.SEMI_SIDE]: "Semi-Side View",
        [ViewType.SIDE]: "Side View",
        [ViewType.BACK]: "Back View"
    },
    view_labels: {
        [ViewType.FRONT]: "FRONT",
        [ViewType.SEMI_SIDE]: "3/4 SIDE",
        [ViewType.SIDE]: "SIDE",
        [ViewType.BACK]: "BACK"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (Natural 45°)',
        [PoseType.T_POSE]: 'T-POSE (Horizontal 90°)',
        [PoseType.I_POSE]: 'I-POSE (Straight)',
    },
    usage_steps: [
      {
        title: "Prepare Character Art (Input)",
        desc: "Upload a full-body frontal image of your character, or use a text prompt to generate a new one.",
        bullets: [
          "Images with simple backgrounds yield better results.",
          "A-Pose (arms slightly apart) is ideal."
        ]
      },
      {
        title: "Generate 4-View Reference (Step 1)",
        desc: "Click [Generate 4-View Reference]. AI will automatically create Side, Back, and Semi-Side (3/4) views.",
        bullets: [
          "The character's pose will be normalized to a standard pose (A-Pose/T-Pose).",
          "You can regenerate or refine details of each view using the 'Modify' feature."
        ]
      },
      {
        title: "Select Parts & Generate Sheets (Step 2)",
        desc: "Select the parts you need detailed sheets for (e.g., Outfit, Weapon, Face).",
        bullets: [
          "You can add custom parts (e.g., Mechanical Arm, Cape) via the 'Add Custom Part' input.",
          "Click [Generate Concept Sheet] to create detailed analysis sheets for each selected part."
        ]
      },
      {
        title: "Export Result",
        desc: "Save the complete sheet as a JPG image, or export just the clean assets separately.",
        bullets: []
      }
    ],
    patch_notes_list: [
      { version: "v1.34", desc: "Update: Upscale logic improved (Fidelity focused). Added save button descriptions." },
      { version: "v1.33", desc: "Feature: Partial/Full Upscale(4K). Partial Regeneration(Undo/Redo)." },
      { version: "v1.32", desc: "Feature: Reference Balance Slider. Batch Actions." },
      { version: "v1.29", desc: "Feature: Full Korean localization. Added 'Buy Me a Coffee' support." },
      { version: "v1.28", desc: "Feature: Multi-language support added." }
    ],
    batch_upscale: "Upscale Selected",
    batch_regenerate: "Regenerate Selected",
    ref_balance_title: "Reference Balance",
    ref_original: "Original Heavy",
    ref_generated: "Generated Heavy",
    batch_parts_undo: "Undo All",
    batch_parts_redo: "Redo All",
    batch_parts_upscale: "Upscale All",
    batch_parts_regen: "Regen All",
    btn_use_generated: "Use Generated",
    btn_use_original: "Use Original",
  },
  [Language.JA]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.34 • Created by Mookxy • snu07001@naver.com",
    copyright_title: "著作権に関する注意",
    copyright_msg: "他人の著作物を無断で使用して発生するすべての問題の責任はユーザーにあります。必ずご自身の創作物または使用権限のある画像のみをアップロードして使用してください。",
    usage_guide: "利用ガイド",
    usage_desc: "キャラクターシートの作成手順を確認します。",
    patch_notes: "パッチノート",
    patch_desc: "最新のアップデート内容を確認します。",
    view_multi: "4面図モード",
    view_all: "全ビュー表示",
    mode_single: "単一画像モード (原画のみ参考)",
    mode_text: "テキストからキャラクター生成",
    input_prompt: "キャラクター説明 (Prompt)",
    input_placeholder: "例：未来的なサイバーパンクの女戦士、ネオンブルーのジャケット、黒いカーゴパンツ、赤いゴーグル着用...",
    style_ref: "スタイル参考 (任意)",
    drag_style: "* 画像をドラッグ＆ドロップまたは貼り付けて、スタイルや構図を参考にできます。",
    pose_select: "標準ポーズ選択 (Pose)",
    part_select: "生成パーツ選択",
    custom_part: "その他パーツ追加...",
    btn_generate_text: "キャラクター原画生成",
    btn_analyze_single: "単一画像分析開始",
    btn_generate_views: "4面図リファレンス生成",
    step0: "Step 0: テキストから生成 (完了時に自動でStep 1へ移動)",
    step1_single: "Step 1: 画像分析およびパーツ抽出",
    step1_multi: "Step 1: ポーズ正規化 & 4面図(側/半側/後) 自動生成",
    hint_bottom: "👇 下のシートで [コンセプトシート生成] ボタンを押して作業を続けてください",
    status_waiting: "待機中",
    error_no_ref: "参照画像がありません。",
    error_view_fail: "ビュー生成失敗。",
    status_text_gen: "テキストからキャラクター生成中...",
    status_ref_check: "リファレンス確認中...",
    status_3q: "立体感分析のための半側面(3/4)ビュー生成中...",
    status_norm: "ポーズ正規化中",
    status_4view: "4面図完成中...",
    status_palette: "カラーパレット抽出中...",
    status_analyze: "構造および色彩分析中...",
    error_no_part: "分析の結果、選択したパーツが検出されませんでした。",
    status_sheet: "詳細シート生成中...",
    error_sheet: "シート生成中にエラーが発生しました。",
    error_select_part: "生成するパーツを1つ以上選択してください。",
    btn_clean_save: "画像のみ結合保存 (Clean)",
    btn_full_save: "全体シート保存 (JPG)",
    btn_zip_save: "ZIP保存",
    btn_upscale: "アップスケール (4K)",
    dl_zip_desc: "全パーツ個別ファイル圧縮",
    dl_clean_desc: "テキスト除外アセットのみ結合",
    dl_full_desc: "全体画面キャプチャ保存",
    header_title: "キャラクターシート",
    header_theme: "カラーテーマ",
    main_ref: "メインリファレンス",
    analysis_4view: "4面図精密分析",
    reset: "初期化",
    btn_regen_sheet: "シート再生成",
    btn_gen_sheet: "コンセプトシート生成",
    style_override: "スタイル参考 (例: 白黒スケッチ, 3Dレンダリング...)",
    style_note: "* 入力したスタイルを基に詳細シートが生成されます。(空欄の場合は原画スタイル維持)",
    upscale_hint: "* 4面図をすべてアップスケールした後にシートを生成すると、より詳細な結果が得られます。",
    ref_balance_note: "* 参照バランス：[オリジナル]に近いほどアップロード画像を、[生成]に近いほどAI生成4面図を反映します。",
    style_ref_note: "* スタイル参考：テキスト入力欄に希望する画風（例：3Dレンダリング、ドット絵）を入力するとスタイルが変更されます。",
    original: "オリジナル",
    source: "ソース",
    user_upload: "ユーザーアップロード",
    palette_title: "カラーパレット",
    extracted_colors: "抽出カラー",
    color: "カラー",
    source_chips: "参照画像",
    manual: "手動",
    add: "追加",
    no_asset: "生成された画像なし",
    generate: "生成",
    designing: "デザイン中...",
    analyzing_desc: "構造分析およびシート生成中",
    refine_design: "デザイン修正",
    applied_changes: "適用された修正",
    modify_request: "修正リクエスト",
    confidential: "機密資産シート • 無断配布禁止",
    powered_by: "Google Gemini ベース • 制作: Mookxy",
    ref_asset_sheet: "リファレンス資産シート",
    project_ref: "プロジェクト: リファレンス資産",
    modal_copyright_title: "著作権および使用権限の確認",
    modal_copyright_body: "アップロードした画像は他人の著作権を侵害していませんか？\n\nCharSheet AIは、アップロードされた画像を基に新しい画像を生成します。\n\n他人の創作物を無断で使用して発生するすべての法的責任はユーザー本人にあります。\n必ずご自身の創作物、または使用権限のある画像のみを使用して進めてください。",
    modal_confirm: "はい、確認しました。生成開始",
    modal_cancel: "キャンセル",
    drop_here: "画像をドロップ",
    upload: "アップロード",
    analysis_label: "分析",
    buy_coffee: "開発者にコーヒーを奢る ☕",
    coffee_modal_title: "開発者を応援する",
    coffee_modal_body: "CharSheet AIは役に立ちましたか？\n皆様の応援が継続的なアップデートと新機能開発の大きな力になります！\n\n☕ KakaoBank: 3333-06-3849386 (Mookxy)",
    btn_coffee_link: "コーヒーを奢る (aCoffee)",
    btn_compare: "オリジナルと比較",
    part_desc_gloves: "手の甲および手のひらビューを含む。素材テクスチャ詳細。",
    part_desc_top: "A-Pose衣装シミュレーション分離。縫い目およびしわ分析。",
    part_desc_bottom: "ボトムス分離。ステッチおよびポケット配置。",
    part_desc_jacket: "アウターレイヤー分離。裏地および留め具構造。",
    part_desc_face: "表情シート：正面、半側面、側面ビュー。",
    part_desc_hair: "構造分析：ボリューム、流れおよび生え際。",
    part_desc_bag: "ストラップ接続部、バックル、収納スペース可視化。",
    part_desc_accessory: "複雑な形状のマクロズーム。サイズ比率参照。",
    part_desc_shoes: "靴の正面、側面、背面、ソール詳細。",
    part_desc_weapon: "全体形状およびグリップ/刃部分拡大。",
    part_desc_custom: "ユーザー指定の詳細リクエスト。",
    part_desc_standard: "標準平面投影。",
    parts: {
        [PartType.FACE]: '顔 / 表情',
        [PartType.HAIR]: '髪 / スタイル',
        [PartType.HAT]: '帽子 / ヘッドウェア',
        [PartType.JACKET]: 'ジャケット / アウター',
        [PartType.TOP]: 'トップス / インナー',
        [PartType.BOTTOM]: 'ボトムス / パンツ',
        [PartType.SHOES]: '靴 / ブーツ',
        [PartType.GLOVES]: '手袋 / 手',
        [PartType.WEAPON]: '武器 / アイテム',
        [PartType.BAG]: 'バッグ / 装備',
        [PartType.ACCESSORY]: 'アクセサリー / 装飾',
    },
    views: {
        [ViewType.FRONT]: "正面 (Front)",
        [ViewType.SEMI_SIDE]: "半側面 (Semi-Side)",
        [ViewType.SIDE]: "側面 (Side)",
        [ViewType.BACK]: "背面 (Back)"
    },
    view_labels: {
        [ViewType.FRONT]: "FRONT",
        [ViewType.SEMI_SIDE]: "3/4 SIDE",
        [ViewType.SIDE]: "SIDE",
        [ViewType.BACK]: "BACK"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (自然な45度)',
        [PoseType.T_POSE]: 'T-POSE (水平90度)',
        [PoseType.I_POSE]: 'I-POSE (直立)',
    },
    usage_steps: [
      {
        title: "キャラクター原画準備 (入力)",
        desc: "キャラクターの正面全身画像をアップロードするか、テキストプロンプトを使用して新しいキャラクターを生成してください。",
        bullets: [
          "背景が複雑でない画像の方が認識率が高いです。",
          "A-Pose（腕を少し広げた姿勢）が最も理想的です。"
        ]
      },
      {
        title: "4面図リファレンス生成 (Step 1)",
        desc: "[4面図リファレンス生成] ボタンをクリックすると、AIがキャラクターの側面、背面、半側面(45度)ビューを自動生成します。",
        bullets: [
          "この過程でキャラクターの姿勢が標準ポーズ(A-Pose/T-Pose)に正規化されます。",
          "生成された各ビューは「修正リクエスト」機能を通じて再生成したり、詳細を調整できます。"
        ]
      },
      {
        title: "パーツ選択およびシート生成 (Step 2)",
        desc: "詳細図面が必要な部位（衣装、武器、顔など）を選択してください。",
        bullets: [
          "標準パーツ以外に「その他パーツ」入力欄に希望する部位（例：機械の腕、マント）を入力して追加できます。",
          "[コンセプトシート生成] ボタンを押すと、選択した各パーツの詳細分析シートが生成されます。"
        ]
      },
      {
        title: "結果のエクスポート",
        desc: "完成したシートはJPG画像として全体を保存するか、きれいに整理されたアセット(Asset)ページのみを別途保存できます。",
        bullets: []
      }
    ],
    patch_notes_list: [
      { version: "v1.34", desc: "Update: アップスケールロジック改善（スタイル維持）。保存ボタン説明追加。" },
      { version: "v1.33", desc: "Feature: 部分/全体4Kアップスケール。部分再生成(Undo/Redo)。" },
      { version: "v1.32", desc: "Feature: 参照バランススライダー。バッチ操作(Batch Action)。" },
      { version: "v1.29", desc: "Feature: UI全体のローカライズ。「開発者にコーヒーを奢る」機能追加。" },
      { version: "v1.28", desc: "Feature: 多言語サポート追加。" }
    ],
    batch_upscale: "選択項目をアップスケール",
    batch_regenerate: "選択項目を再生成",
    ref_balance_title: "参照バランス (Reference Balance)",
    ref_original: "オリジナル重視",
    ref_generated: "生成重視",
    batch_parts_undo: "すべて元に戻す",
    batch_parts_redo: "すべてやり直す",
    batch_parts_upscale: "すべてアップスケール",
    batch_parts_regen: "すべて再生成",
    btn_use_generated: "生成画像を使用",
    btn_use_original: "アップロード画像を使用",
  },
  [Language.ZH]: {
    title: "CharSheet AI",
    desc: "Charsheet AI v1.34 • Created by Mookxy • snu07001@naver.com",
    copyright_title: "版权警告",
    copyright_msg: "因擅自使用他人作品而产生的一切问题由用户承担。请务必仅上传本人的创作或拥有使用权限的图片。",
    usage_guide: "使用指南",
    usage_desc: "查看详细的角色表生成步骤。",
    patch_notes: "更新日志",
    patch_desc: "查看最新更新内容。",
    view_multi: "四视图模式",
    view_all: "查看全部",
    mode_single: "单图模式 (仅参考原画)",
    mode_text: "文本生成角色",
    input_prompt: "角色描述 (Prompt)",
    input_placeholder: "例如：未来赛博朋克女战士，霓虹蓝夹克，黑色工装裤，佩戴红色护目镜...",
    style_ref: "风格参考 (可选)",
    drag_style: "* 拖拽或粘贴图片以参考风格或构图。",
    pose_select: "选择标准姿势 (Pose)",
    part_select: "选择生成部位",
    custom_part: "添加其他部位...",
    btn_generate_text: "生成角色原画",
    btn_analyze_single: "开始单图分析",
    btn_generate_views: "生成四视图参考",
    step0: "Step 0: 从文本生成角色 (完成后自动进入Step 1)",
    step1_single: "Step 1: 图像分析及部位提取",
    step1_multi: "Step 1: 姿势标准化 & 自动生成四视图(侧/半侧/后)",
    hint_bottom: "👇 点击下方的 [生成概念图] 按钮继续操作",
    status_waiting: "待机中",
    error_no_ref: "未找到参考图片。",
    error_view_fail: "视图生成失败。",
    status_text_gen: "正在从文本生成角色...",
    status_ref_check: "正在检查参考...",
    status_3q: "正在生成用于立体感分析的半侧面(3/4)视图...",
    status_norm: "正在标准化姿势",
    status_4view: "正在完成四视图...",
    status_palette: "正在提取调色板...",
    status_analyze: "正在分析结构与色彩...",
    error_no_part: "分析结果：未检测到选定的部位。",
    status_sheet: "正在生成详细图表...",
    error_sheet: "生成图表时发生错误。",
    error_select_part: "请至少选择一个部位。",
    btn_clean_save: "仅保存图片拼接 (Clean)",
    btn_full_save: "保存完整图表 (JPG)",
    btn_zip_save: "保存为ZIP",
    btn_upscale: "放大 (4K)",
    dl_zip_desc: "所有部位单独文件压缩",
    dl_clean_desc: "仅合并图像资源，无文本",
    dl_full_desc: "完整屏幕截图保存",
    header_title: "角色设计图表",
    header_theme: "色彩主题",
    main_ref: "主要参考",
    analysis_4view: "四视图精密分析",
    reset: "重置",
    btn_regen_sheet: "重新生成图表",
    btn_gen_sheet: "生成概念图",
    style_override: "风格参考 (例: 黑白草图, 3D渲染...)",
    style_note: "* 将根据输入的风格生成详细图表。(留空则保持原画风格)",
    upscale_hint: "* 在生成图表之前对四视图进行放大（Upscale），可以获得更详细的结果。",
    ref_balance_note: "* 参考平衡：越接近 [Original] 使用上传图片；越接近 [Generated] 使用 AI 生成视图。",
    style_ref_note: "* 风格参考：在文本输入框中输入所需风格（例如：3D 渲染、像素艺术）以更改图表风格。",
    original: "原画",
    source: "来源",
    user_upload: "用户上传",
    palette_title: "调色板",
    extracted_colors: "提取颜色",
    color: "颜色",
    source_chips: "参考图片",
    manual: "手动",
    add: "添加",
    no_asset: "无生成图片",
    generate: "生成",
    designing: "设计中...",
    analyzing_desc: "结构分析及图表生成中",
    refine_design: "修改设计",
    applied_changes: "已应用修改",
    modify_request: "修改请求",
    confidential: "机密资产图表 • 禁止擅自传播",
    powered_by: "基于 Google Gemini • 制作: Mookxy",
    ref_asset_sheet: "参考资产图表",
    project_ref: "项目: 参考资产",
    modal_copyright_title: "版权及使用权限确认",
    modal_copyright_body: "您上传的图片是否侵犯了他人的版权？\n\nCharSheet AI 基于您上传的图片生成新图像。\n\n因擅自使用他人创作而产生的一切法律责任由用户本人承担。\n请务必确认使用的是本人的创作或拥有使用权限的图片。",
    modal_confirm: "是的，我确认。开始生成",
    modal_cancel: "取消",
    drop_here: "图片拖放到此处",
    upload: "上传",
    analysis_label: "分析",
    buy_coffee: "请开发者喝咖啡 ☕",
    coffee_modal_title: "支持开发者",
    coffee_modal_body: "CharSheet AI 对您有帮助吗？\n您的支持是持续更新和开发新功能的巨大动力！",
    btn_coffee_link: "请我喝咖啡 (aCoffee)",
    btn_compare: "与原图比较",
    part_desc_gloves: "包含手背及手掌视图。材质纹理细节。",
    part_desc_top: "A-Pose 服装模拟分离。接缝及褶皱分析。",
    part_desc_bottom: "下装分离。缝线及口袋位置。",
    part_desc_jacket: "外层分离。内衬及闭合结构。",
    part_desc_face: "表情图表：正面、半侧面、侧面视图。",
    part_desc_hair: "结构分析：体积、流向及发际线。",
    part_desc_bag: "背带连接处、扣具、收纳空间可视化。",
    part_desc_accessory: "复杂形状的微距放大。尺寸比例参考。",
    part_desc_shoes: "鞋子的正面、侧面、背面、鞋底细节。",
    part_desc_weapon: "整体形状及握柄/刃部放大。",
    part_desc_custom: "用户指定的详细请求。",
    part_desc_standard: "标准平面投影。",
    parts: {
        [PartType.FACE]: '脸部 / 表情',
        [PartType.HAIR]: '发型 / 风格',
        [PartType.HAT]: '帽子 / 头饰',
        [PartType.JACKET]: '外套 / 大衣',
        [PartType.TOP]: '上衣 / 内搭',
        [PartType.BOTTOM]: '下装 / 裤子',
        [PartType.SHOES]: '鞋 / 靴子',
        [PartType.GLOVES]: '手套 / 手',
        [PartType.WEAPON]: '武器 / 道具',
        [PartType.BAG]: '包 / 装备',
        [PartType.ACCESSORY]: '饰品 / 珠宝',
    },
    views: {
        [ViewType.FRONT]: "正面 (Front)",
        [ViewType.SEMI_SIDE]: "半侧面 (Semi-Side)",
        [ViewType.SIDE]: "侧面 (Side)",
        [ViewType.BACK]: "背面 (Back)"
    },
    view_labels: {
        [ViewType.FRONT]: "FRONT",
        [ViewType.SEMI_SIDE]: "3/4 SIDE",
        [ViewType.SIDE]: "SIDE",
        [ViewType.BACK]: "BACK"
    },
    poses: {
        [PoseType.A_POSE]: 'A-POSE (自然45度)',
        [PoseType.T_POSE]: 'T-POSE (水平90度)',
        [PoseType.I_POSE]: 'I-POSE (直立)',
    },
    usage_steps: [
      {
        title: "准备角色原画 (输入)",
        desc: "上传角色的正面全身图像，或使用文本提示生成新角色。",
        bullets: [
          "背景简单的图片识别率更高。",
          "A-Pose（手臂微张的姿势）最为理想。"
        ]
      },
      {
        title: "生成四视图参考 (Step 1)",
        desc: "点击 [生成四视图参考] 按钮，AI 将自动生成角色的侧面、背面和半侧面 (45度) 视图。",
        bullets: [
          "在此过程中，角色的姿势将被标准化为标准姿势 (A-Pose/T-Pose)。",
          "生成的每个视图都可以通过“修改请求”功能重新生成或微调细节。"
        ]
      },
      {
        title: "选择部位并生成图表 (Step 2)",
        desc: "选择需要详细图表的部位（如服装、武器、脸部等）。",
        bullets: [
          "除了标准部位外，还可以通过“添加其他部位”输入框添加自定义部位（例如：机械臂、披风）。",
          "点击 [生成概念图] 按钮，将为每个选定的部位生成详细的分析图表。"
        ]
      },
      {
        title: "导出结果",
        desc: "您可以将完整的图表保存为 JPG 图片，或者单独保存整理好的资产 (Asset) 页面。",
        bullets: []
      }
    ],
    patch_notes_list: [
      { version: "v1.34", desc: "Update: 优化放大逻辑（保持风格）。添加保存按钮说明。" },
      { version: "v1.33", desc: "Feature: 部分/全部 4K 放大。部分重新生成 (Undo/Redo)。" },
      { version: "v1.32", desc: "Feature: 参考平衡滑块。批量操作 (Batch Action)。" },
      { version: "v1.29", desc: "Feature: 全面本地化UI。添加“请开发者喝咖啡”功能。" },
      { version: "v1.28", desc: "Feature: 添加多语言支持。" }
    ],
    batch_upscale: "批量放大",
    batch_regenerate: "批量重新生成",
    ref_balance_title: "参考平衡 (Reference Balance)",
    ref_original: "偏向原图",
    ref_generated: "偏向生成",
    batch_parts_undo: "全部撤销",
    batch_parts_redo: "全部重做",
    batch_parts_upscale: "全部放大",
    batch_parts_regen: "全部重新生成",
    btn_use_generated: "使用生成图",
    btn_use_original: "使用上传图",
  },
};
